server:
  port: 8080
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:file:classpath:db/sui
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: true